name: CI
on: [push]
jobs:
  unit-test-javascript:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./javascript
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build javascript docker image
        run: docker build -t leetcode-javascript:latest .
      - name: Run test
        run: docker run --rm leetcode-javascript:latest
  unit-test-scala:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scala
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run tests
        run: sbt test
  unit-test-python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run test
        run: docker-compose up
  unit-test-csharp:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./csharp
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: dotnet test --no-restore --verbosity normal
